version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  e2e:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run e2e
workflows:
    e2e:
      jobs:
        - e2e